version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=GCB_Challenge
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
      - MYSQL_DATABASE=GCB_Challenge
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysqldb    
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    links:
      - mysqldb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
volumes: 
  db: